

# DB 접속 정보와 파일 업로드 설정
spring:
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: asd
            client-secret: asd
            redirect-uri: http://localhost:8888/login/oauth2/code/google
            scope:
            - email
            - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

# mybatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fitconnect.**
  