spring:
  profiles:
    group:
      local: local
      server: server
default:
  string: default property
  
---
spring:
  config:
    import: "classpath:custom-${spring.profiles.active}.properties"
    activate:
      on-profile: local
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: 
    password: 
server:
  port: 8888
  servlet:
#    context-path: /fitconnect
    session:
      tracking-modes: cookie
---
spring:
  config:
    import: "classpath:custom-${spring.profiles.active}.properties"
    activate:
      on-profile: server
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@52.78.38.12:1521:xe?oracle.jdbc.timezoneAsRegion=false
    username: 
    password: 
server:
  port: 8080
  servlet:
#    context-path: /fitconnect
    session:
      tracking-modes: cookie
---
      