server:
  port: 9999
  servlet:
    context-path: /fitconnect
    session:
      tracking-modes: cookie

# DB 접속 정보와 파일 업로드 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
# mybatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fitconnect.**
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tags-sorter: alpha
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
